# Generated by Django 3.0.5 on 2024-06-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_db',
            name='crop_size',
        ),
        migrations.AddField(
            model_name='crop_db',
            name='land_size',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
